### ISSUE TITLE
Feature ideas

### ISSUE THREAD

**Issue by BenRacicot** [moebius-mlm/ng-validators#1]
Hey Moebius, Awesome repo here. I've bene on the hunt for a really well written and documented collection of custom validators for Angular 2+. Are you interested in growing this repo? I would be willing to commit all my custom validators if so.

I'm looking for alpha characters only and numeric characters only validators for name fields.

Something like this for alpha only:
```
import { FormControl } from '@angular/forms';

export class AlphaOnlyValidator {
    static invalidAlphaOnly(control: FormControl): { [key: string]: boolean } {
        if (control.value.length && !control.value.match(/^[a-z]+$/i)) {
            return { invalidAlphaNumeric: true };
        }
        return null;
    }
}
```

**Comment by slavafomin** [comment]
Hello Ben! Thank you for getting in touch!

We don't have enough resources to actively grow this repo at the moment, but if you are willing to be an active force, I think we can figure something out.

Actually, I was thinking about implementing this in layers. The first layer could be a very low-level collection of generic validators, written in TypeScript, which could be used in any project (server-side, client-side etc). Then, the second-level layer will take care of integration of these validators to popular libraries and frameworks, like Angular and such.

This repository was just a rough idea to solve the actual need in Angular 2, but I think the concept could be extended further than that.

If you are willing to collaborate on this, then we can figure out the interface for the validators and then we can start building a list of most needed ones, implementing them along the way. I will be happy to guide this process an to help with organizing the effort and maintaining the meaningful API, integration and such.

**Comment by BenRacicot** [comment]
@slavafomin absolutely! I would love to help and even better, to be guided on how to help. It's strange that there isn't any 'all-inclusive" validator libraries out there. 

Feel free to reach out BenjaminRacicotATgmail.com and explain how I should go about helping on this repo. I like the concept you've laid out with low-level generic validators in TS. I am strictly Node/Angular at this point in my career so this sounds great!

**Comment by slavafomin** [comment]
@BenRacicot I'm glad to hear that! I've created a new repo to actually host those low-level validators. And here's the discussion: https://github.com/betsol/ts-validators/issues/1. Please, feel free to share your thoughts on this. I would prefer to keep this process public (so out of private E-Mail loop), so anyone could participate.
