### ISSUE TITLE
Expected validator to return Promise or Observable.

### ISSUE THREAD

**Issue by digibum** [moebius-mlm/ng-validators#2]
I am getting this error on Angular 4+

`Expected validator to return Promise or Observable.`

Using like this:
`this.newPasswordForm = this.formBuilder.group({
password: ['', [Validators.required, Validators.minLength(6)]],
password2: ['', [Validators.required, matchOtherValidator("password")]]
});`

**Comment by digibum** [comment]
Don't know how but it's working now xD

**Comment by slavafomin** [comment]
Hello! Thank you for your interest in this module!

I'm glad you've figured this out. Actually Angular has a built-in E-Mail validator: `Validators.email`.

**Comment by Vimallakzz** [comment]
It means that you have to **add multiple validators in array**

.
Example:

**With Error**

    profileFormGroup = {
      budget: [null, Validators.required, Validators.min(1)]
    };

Above one throws error that **validator to return Promise or Observable**

**Fix:**

    profileFormGroup = {
      budget: [null, [Validators.required, Validators.min(1)]]
    };

**Explanation:**

In angular Reactive form validation done by using in-built validators which could given in array in 2nd postion, when **multiple validators used**.

> FIELD_KEY: [INITIAL_VALUE, [LIST_OF_VALIDATORS]]
